const animals = [{
    name: "Lion",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Shark",
    type: "vertebrate",
    habitat: "water"
}, {
    name: "Snail",
    type: "invertebrate",
    habitat: "land"
}, {
    name: "Sparrow",
    type: "vertebrate",
    habitat: "air"
}, {
    name: "Platypus",
    type: "vertebrate",
    habitat: "water"
}, {
    name: "Caterpillar",
    type: "invertebrate",
    habitat: "land"
}, {
    name: "Star Fish",
    type: "invertebrate",
    habitat: "water"
}, {
    name: "Falcon",
    type: "vertebrate",
    habitat: "air"
}, {
    name: "Dolphin",
    type: "vertebrate",
    habitat: "water"
}, {
    name: "Mosquito",
    type: "invertebrate",
    habitat: "air"
}, {
    name: "Lady Bug",
    type: "invertebrate",
    habitat: "air"
}, {
    name: "Snake",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Lobster",
    type: "invertebrate",
    habitat: "water"
}, {
    name: "Panda",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Vulture",
    type: "vertebrate",
    habitat: "air"
}, {
    name: "Bee",
    type: "invertebrate",
    habitat: "air"
}, {
    name: "Octopus",
    type: "invertebrate",
    habitat: "water"
}, {
    name: "Lemur",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Bat",
    type: "vertebrate",
    habitat: "air"
}, {
    name: "Whale",
    type: "vertebrate",
    habitat: "water"
}, {
    name: "Sloth",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Salmon",
    type: "vertebrate",
    habitat: "water"
}, {
    name: "Rabbit",
    type: "vertebrate",
    habitat: "land"
}, {
    name: "Eagle",
    type: "vertebrate",
    habitat: "air"
}
];

module.exports = animals;